# Site settings
title: Ölandsbröllop.se
email: andreas@enigma.cc
author: Andreas Fransson
url: http://ölandsbröllop.se

# Configatron
url_without_protocol: ölandsbröllop.se
fb_app_id: '1436869663260887'
ga_tracking_code: UA-31649925-3
time_tag_format: '%FT%T%Z'

wedding_date: 2014-07-15 15:00

# Build settings
permalink: pretty
timezone: Europe/Stockholm
